package org.example

data class Node(var data: Int) {
    val children = ArrayList<Node>()
}

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
fun main() {
    val input =
        intArrayOf(10, 20, 50, -1, 60, -1, -1, 30, 70, -1, 80, 110, -1, 120, -1, -1, 90, -1, -1, 40, 100, -1, -1, -1)
    val root = createTree(input)

    val input2 = intArrayOf(
        10, 20, 50, -1, 60, -1, -1, 30, 70, -1, 80, 110, -1, 120, -1, 130, -1, -1, 90, -1, -1, 40, 100, -1, -1, -1
    )
    val root2 = createTree(input2)

    println("---------------")
    println("Display Tree")
    displayTree(root)
    println("---------------")
    println("Size of Tree")
    sizeOfTree(root).let(::println)
    println("---------------")
    println("Maximum in Tree")
    findMaximum(root).let(::println)
    println("---------------")
    println("Height of Tree w.r.t. edges")
    findHeight(root).let(::println)
    println("---------------")
    println("Euler/DF Traversal of tree")
    depthTraversal(root)
    println("---------------")
    println("BF/Level order of tree")
    levelOrderTraversal(root)
    println("---------------")
    println("BF/Level order of tree using delimiter")
    levelOrderLineWiseUsingDelimiter(root)
    println("---------------")
    println("BF/Level order of tree using count")
    levelOrderLineWiseUsingCount(root)
    println("---------------")
    println("BF/Level order of tree using pair")
    levelOrderLineWiseUsingPair(root)
    println("---------------")
    println("BF/Level order line wise using 2 queues")
    levelOrderLineWise2Queue(root)
    println("---------------")
    println("BF/Level order zig zag of tree")
    levelOrderZigZag(root)
    println("---------------")
    println("BF/Level order zig zag of tree using 2 stacks")
    levelOrderZigZag2Stacks(root)
    println("---------------")
//    println("Mirror the tree")
//    mirrorTheTree(root)
//    displayTree(root)
//    println("---------------")
//    println("Remove leaf nodes")
//    removeLeafNodes(root)
//    displayTree(root)
//    println("---------------")
//    println("Linearize a tree")
//    linearizeTree(root)
//    displayTree(root)
//    println("---------------")
//    println("Linearize a tree efficient")
//    linearizeTreeEfficient(root)
//    displayTree(root)
//    println("---------------")
    println("Is 110 present in tree ?")
    println(if (findElement(root, 110)) "Present" else "Absent")
    println("---------------")
    println("If 110 present, give path ?")
    println(nodeToRootPath(root, 110)).let(::println)
    println("---------------")
    println("Find lowest common ancestor of 110 and 20")
    println(lowestCommonAncestor(110, 40, root))
    println("---------------")
    println("Distance between node in terms of edges")
    println(distanceBetweenNodes(100, 50, root))
    println("---------------")
    println("Are trees similar in shape")
    println(similarInShape(root, root2))
    println("---------------")
    println("Are trees mirror in shape")
    var r1 = createTree(intArrayOf(10, 20, 40, -1, 70, -1, -1, 30, 50, -1, 60, -1, -1, -1))
    val r2 = createTree(intArrayOf(10, 20, -1, 30, -1, -1))
    println(isMirrorInShape(r1, r2))
    println("---------------")
    println("Is tree symmetric ?")
    println(isSymmetricInShape(r1))
    println("---------------")
    println("MultiSolver:")
    multiSolver(root, 0)
    println(
        """
    Count -> $size
    Min value -> $minValue
    Max value -> $maxValue
    Height -> $height""".trimIndent()
    )
    println("---------------")
    println("Find predecessor and successor")
    val (p, s) = findPredecessorAndSuccessor(root, 130)
    println("Predecessor: $p and Successor: $s")
    println("---------------")
    println("Find predecessor and successor refined")
    val (pre, suc) = findPS(root, element = 10)
    println("Predecessor: $pre and Successor: $suc")
    println("---------------")
    println("Ceil and floor")
    val (ceil, floor) = findCeilAndFloor(root, 60)
    println("Ceil: $ceil and Floor: $floor")
    println("---------------")
    println("Find kth largest element")
    kLargestElement(root, 7).let(::println)
    println("---------------")
    println("Node with max subtree sum")
    r1 = createTree(
        intArrayOf(
            10, 20, -50, -1, -60, -1, -1, 30, -70, -1, 80, -110, -1, 120, -1, -1, 90, -1, -1, 40, -100, -1, -1, -1
        )
    )
    displayTree(r1)
    nodeMaxSubTreeSum(r1).let(::println)
    println("---------------")
    println("Diameter of generic tree")
    r1 = createTree(
        intArrayOf(
            10, 20, 50, 70, 80, -1, -1, -1, 60, 80, 90, -1, -1, -1, -1, 30, -1, -1
        )
    )
    displayTree(r1)
    findDiameter(r1).let(::println)
    println("---------------")
    println("Iteratively traversing the tree")
    iterativeTraversal(r1)

}
